In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')
valid_df = pd.read_csv('valid.csv')

In [3]:
train_df.head()

,ID,Label,Statement,Subject(s),Speaker,Speaker's job title,State,Party,Barely true counts,False counts,Half true counts,Mostly true counts,Pants on fire counts,Context
0,2635.json,FALSE,Says the Annies List political group supports ...,abortion,dwayne-bohac,State representative,Texas,republican,0.0,1.0,0.0,0.0,0.0,a mailer
1,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.
2,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver
3,1123.json,FALSE,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release
4,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN

In [4]:
train_df.shape

(10240, 14)

In [5]:
train_df.describe()

,Barely true counts,False counts,Half true counts,Mostly true counts,Pants on fire counts
count,10238.000000,10238.000000,10238.000000,10238.000000,10238.000000
mean,11.533210,13.286482,17.133718,16.434265,6.201407
std,18.973764,24.112936,35.846511,36.151688,16.128927
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,2.000000,3.000000,3.000000,1.000000
75%,12.000000,12.000000,13.000000,11.000000,5.000000
max,70.000000,114.000000,160.000000,163.000000,105.000000

In [6]:
train_df.isnull().sum()

ID                         0
Label                      0
Statement                  0
Subject(s)                 2
Speaker                    2
Speaker's job title     2898
State                   2210
Party                      2
Barely true counts         2
False counts               2
Half true counts           2
Mostly true counts         2
Pants on fire counts       2
Context                  102
dtype: int64

In [7]:
test_df.head()

,ID,Label,Statement,Subject(s),Speaker,Speaker's job title,State,Party,Barely true counts,False counts,Half true counts,Mostly true counts,Pants on fire counts,Context
0,11972.json,TRUE,Building a wall on the U.S.-Mexico border will...,immigration,rick-perry,Governor,Texas,republican,30,30,42,23,18,Radio interview
1,11685.json,FALSE,Wisconsin is on pace to double the number of l...,jobs,katrina-shankland,State representative,Wisconsin,democrat,2,1,0,0,0,a news conference
2,11096.json,FALSE,Says John McCain has done nothing to help the ...,"military,veterans,voting-record",donald-trump,President-Elect,New York,republican,63,114,51,37,61,comments on ABC's This Week.
3,5209.json,half-true,Suzanne Bonamici supports a plan that will cut...,"medicare,message-machine-2012,campaign-adverti...",rob-cornilles,consultant,Oregon,republican,1,1,3,1,1,a radio show
4,9524.json,pants-fire,When asked by a reporter whether hes at the ce...,"campaign-finance,legal-issues,campaign-adverti...",state-democratic-party-wisconsin,NaN,Wisconsin,democrat,5,7,2,2,7,a web video

In [8]:
test_df.isnull().sum()

ID                        0
Label                     0
Statement                 0
Subject(s)                0
Speaker                   0
Speaker's job title     325
State                   262
Party                     0
Barely true counts        0
False counts              0
Half true counts          0
Mostly true counts        0
Pants on fire counts      0
Context                  17
dtype: int64

In [9]:
test_df.shape

(1267, 14)

In [10]:
valid_df.shape

(1284, 14)

In [11]:
valid_df.isnull().sum()

ID                        0
Label                     0
Statement                 0
Subject(s)                0
Speaker                   0
Speaker's job title     345
State                   279
Party                     0
Barely true counts        0
False counts              0
Half true counts          0
Mostly true counts        0
Pants on fire counts      0
Context                  12
dtype: int64

In [12]:
train_df['Statement'].describe()

count                                                 10240
unique                                                10223
top       On changing the rules for filibusters on presi...
freq                                                      3
Name: Statement, dtype: object

In [13]:
train_df['Statement'].head()

0    Says the Annies List political group supports ...
1    When did the decline of coal start? It started...
2    Hillary Clinton agrees with John McCain "by vo...
3    Health care reform legislation is likely to ma...
4    The economic turnaround started at the end of ...
Name: Statement, dtype: object

In [14]:
train_df['Statement'].tail()

10235    There are a larger number of shark attacks in ...
10236    Democrats have now become the party of the [At...
10237    Says an alternative to Social Security that op...
10238    On lifting the U.S. Cuban embargo and allowing...
10239    The Department of Veterans Affairs has a manua...
Name: Statement, dtype: object

In [15]:
train_df['Statement'].sample(n=5)

3280    More than 80 percent of Georgians dont support...
7208    Each day our nation pays communist China $73.9...
5620    When (Barack Obama) took office, 2.3 million p...
219     On how money from a possible lease of the Ohio...
1838    Congressman Cicilline, when he was the mayor o...
Name: Statement, dtype: object